site_name: Setuav Standard
site_description: Setuav Standard documentation

theme:
  name: material
  font:
    text: Ubuntu
    code: Ubuntu Mono
  logo: assets/logo.svg
  favicon: assets/logo.svg
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep-orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep-orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/contrib/auto-render.min.js
  - javascripts/katex.js

extra_css:
  - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.css

plugins:
  - i18n:
      languages:
        - locale: en
          name: English
          default: true
        - locale: tr
          name: Türkçe
          nav_translations:
            Introduction: Giriş
            Conventions: Temel Esaslar
            Geometry: Geometri
            Overview: Genel Bakış
            Wing: Kanat
            Wing Attachment: Kanat Yerleşimi
            Fuselage: Gövde
            Propulsion: İtki
            Motor: Motor
            Propeller: Pervane
            ESC: ESC
            Battery: Pil
            Mass and Additional Parts: Kütle ve Ek Parçalar

nav:
  - Introduction: index.md
  - Conventions: conventions.md
  - Geometry:
    - Overview: geometry/index.md
    - Fuselage: geometry/fuselage.md
    - Wing: geometry/wing.md
    - Wing Attachment: geometry/wing_attachment.md
  - Propulsion: 
    - Overview: propulsion/index.md
    - Motor: propulsion/motor.md
    - ESC: propulsion/esc.md
    - Propeller: propulsion/propeller.md
    - Battery: propulsion/battery.md
  - Mass and Additional Parts: mass.md
